from __future__ import annotations

from datarepo_doctor.domain.models import (
    AccessMethod,
    FilterClause,
    ProbeSpec,
    SchemaField,
)

PART_COLUMNS = ("p_partkey", "p_name", "p_brand", "p_retailprice")
PART_SCHEMA = (
    SchemaField(name="p_partkey", type="int64"),
    SchemaField(name="p_name", type="string"),
    SchemaField(name="p_brand", type="string"),
    SchemaField(name="p_retailprice", type="decimal"),
)
ORDER_COLUMNS = ("o_orderkey", "o_custkey", "o_orderstatus", "o_totalprice", "o_orderdate")
ORDER_SCHEMA = (
    SchemaField(name="o_orderkey", type="int64"),
    SchemaField(name="o_custkey", type="int64"),
    SchemaField(name="o_orderstatus", type="string"),
    SchemaField(name="o_totalprice", type="decimal"),
    SchemaField(name="o_orderdate", type="date"),
)
SUPPLIER_COLUMNS = ("s_suppkey", "s_name", "s_nationkey", "s_acctbal")
SUPPLIER_SCHEMA = (
    SchemaField(name="s_suppkey", type="int64"),
    SchemaField(name="s_name", type="string"),
    SchemaField(name="s_nationkey", type="int64"),
    SchemaField(name="s_acctbal", type="decimal"),
)

# These hashes are generated by `python -m datarepo_doctor.seed` from the same
# deterministic fixture rows and verified against the checked-in contracts.
PROBES: tuple[ProbeSpec, ...] = (
    ProbeSpec(
        check_id="delta-part-sdk",
        display_name="Part / Delta",
        description="Bounded native Delta retrieval from MinIO through the Python SDK.",
        physical_source="Delta Lake · MinIO",
        catalog="demo_catalog.catalog:DEMO_CATALOG",
        database="tpch",
        table="part",
        access_method=AccessMethod.PYTHON_SDK,
        filters=(FilterClause(column="p_partkey", operator="in", value=[1, 2, 3, 4, 5]),),
        selected_columns=PART_COLUMNS,
        sort_columns=("p_partkey",),
        expected_schema=PART_SCHEMA,
        expected_row_count=5,
        expected_sha256="1489c551b5d646725a51c80555f818a421638fccdedb131087c587d09a05d338",
        timeout_seconds=30,
        phase_offset_minutes=0,
        query_description="Select declared part columns where p_partkey is in [5 fixture keys].",
    ),
    ProbeSpec(
        check_id="parquet-orders-sdk",
        display_name="Orders / Parquet",
        description="Bounded native Parquet retrieval from MinIO through the Python SDK.",
        physical_source="Parquet · MinIO",
        catalog="demo_catalog.catalog:DEMO_CATALOG",
        database="tpch",
        table="orders",
        access_method=AccessMethod.PYTHON_SDK,
        filters=(
            FilterClause(column="o_orderstatus", operator="=", value="O"),
            FilterClause(column="o_orderkey", operator="<=", value=6),
        ),
        selected_columns=ORDER_COLUMNS,
        sort_columns=("o_orderkey",),
        expected_schema=ORDER_SCHEMA,
        expected_row_count=6,
        expected_sha256="466b0332f589944e7765e00ba522f6e3eff6055fac5be27e00e5ca21c9e467a2",
        timeout_seconds=30,
        phase_offset_minutes=5,
        query_description="Select declared order columns for status [redacted] and order key ≤ [redacted].",
    ),
    ProbeSpec(
        check_id="postgres-supplier-function",
        display_name="Supplier / Function",
        description="Bounded PostgreSQL retrieval through a DataRepo custom function table.",
        physical_source="PostgreSQL · function table",
        catalog="demo_catalog.catalog:DEMO_CATALOG",
        database="tpch",
        table="supplier",
        access_method=AccessMethod.PYTHON_SDK,
        arguments={"min_suppkey": 1, "max_suppkey": 4},
        selected_columns=SUPPLIER_COLUMNS,
        sort_columns=("s_suppkey",),
        expected_schema=SUPPLIER_SCHEMA,
        expected_row_count=4,
        expected_sha256="b13456f17019e92c88c46cd62a514dcdba6363d4a57b354b06da96f80ba4b4e9",
        timeout_seconds=20,
        phase_offset_minutes=10,
        query_description="Call supplier with a bounded inclusive key range [redacted].",
    ),
    ProbeSpec(
        check_id="roapi-orders-http",
        display_name="Orders / ROAPI",
        description="Bounded object-backed retrieval through the generated read-only HTTP API.",
        physical_source="Parquet · MinIO via ROAPI",
        catalog="demo_catalog.catalog:DEMO_CATALOG",
        database="tpch",
        table="orders",
        access_method=AccessMethod.ROAPI_HTTP,
        filters=(
            FilterClause(column="o_orderstatus", operator="=", value="O"),
            FilterClause(column="o_orderkey", operator="<=", value=6),
        ),
        selected_columns=ORDER_COLUMNS,
        sort_columns=("o_orderkey",),
        expected_schema=ORDER_SCHEMA,
        expected_row_count=6,
        expected_sha256="466b0332f589944e7765e00ba522f6e3eff6055fac5be27e00e5ca21c9e467a2",
        timeout_seconds=20,
        phase_offset_minutes=15,
        query_description="HTTP SQL select of declared order columns with bounded predicates [redacted].",
    ),
)

_BY_ID = {probe.check_id: probe for probe in PROBES}


def get_probe(check_id: str) -> ProbeSpec:
    try:
        return _BY_ID[check_id]
    except KeyError as exc:
        raise KeyError(f"Unknown check: {check_id}") from exc
